name = input("Hello. What is your name?\n")
print("It's nice to meet you,", end=" ")
print(name, end=". ")
age = input("How old are you?\n")
print("I see that you are still quite young at only", age, end=".\n")
loc = input("Where do you live?\n")
print("Wow! I've always wanted to go to ", loc, end=". Thanks for chatting with me. Bye!")
